from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime
from typing import Literal, Optional


class FcmTokenUpdateRequest(BaseModel):
    """Payload for registering or rotating a provider's FCM device token."""
    model_config = ConfigDict(extra='forbid')

    fcm_token: str = Field(..., min_length=10, description="FCM device token generated by the mobile SDK")
    owner_type: Optional[Literal["doctor", "staff"]] = Field(
        default=None, description="Prototype impersonation: token owner type"
    )
    owner_id: Optional[str] = Field(
        default=None, description="Prototype impersonation: Mongo ObjectId string of token owner"
    )
    platform: Optional[str] = Field(default=None, description="Optional client platform identifier")


class AppointmentCreateRequest(BaseModel):
    """Payload for booking a new appointment. Status is always enforced as PENDING server-side."""
    model_config = ConfigDict(extra='forbid')

    patient_id: str = Field(..., description="MongoDB ObjectId of the patient")
    doctor_id: str = Field(..., description="MongoDB ObjectId of the assigned doctor")
    appointment_time: datetime = Field(..., description="Scheduled slot in UTC")


class AppointmentStatusUpdateRequest(BaseModel):
    """Payload for transitioning an appointment's status."""
    model_config = ConfigDict(extra='forbid')

    status: Literal["ACCEPTED", "REJECTED", "CANCELLED"] = Field(
        ..., description="Target status for the appointment"
    )
