from pydantic import BaseModel, Field, ConfigDict
from typing import Literal
from datetime import datetime

class TokenRegistrationRequest(BaseModel):
    """Payload to strictly map user devices to the backend FCM registry."""
    model_config = ConfigDict(extra='forbid')
    
    owner_id: str = Field(..., description="Internal DB ID of the staff or doctor")
    owner_type: Literal["doctor", "staff"] = Field(..., description="Roles securely partitioned for payload routing")
    fcm_token: str = Field(..., min_length=5, description="FCM device push token natively generated by Mobile apps")

class AppointmentCreateRequest(BaseModel):
    """Payload to handle active widget booking submissions rigidly."""
    model_config = ConfigDict(extra='forbid')
    
    patient_id: str = Field(..., description="ID of the patient requesting the appointment")
    doctor_id: str = Field(..., description="ID of the targeted doctor")
    appointment_time: datetime = Field(..., description="Appointment scheduling block (UTC)")
    
    # 'status' field is intentionally dropped here to prevent active frontend injection tampering. 
    # It must be enforced as 'pending' internally on initialization.
